name: Release Binaries

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  release:
    name: Release Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Run tests
        run: go test ./...

      - name: Build binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -o logtail-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -o logtail-linux-arm64 .
          GOOS=darwin GOARCH=amd64 go build -o logtail-darwin-amd64 .
          GOOS=darwin GOARCH=arm64 go build -o logtail-darwin-arm64 .

      - name: Create Releases
        id: create_releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "${{ github.ref_name }}" \
            logtail-linux-amd64 \
            logtail-linux-arm64 \
            logtail-darwin-amd64 \
            logtail-darwin-arm64
